### PR TITLE
Enhancement - Replaced LG Dialog with Bottom Sheet and Side Sheet

### PR DESCRIPTION
**Pull request by dharamveer-gupta**
Can you please tag this issue as **`hactoberfest`**?  

-----
Task Done - 
- [x] BottomSheet Dialog (Portrait Mode on Mobile device)
- [x] SideSheet Dialog (Tablet & Landscape mode on Mobile device)
-----
**Before Enhancement** ScreenShots - 

- **LG Dialog on Mobile device** - (Portrait Mode)
image
image

- **LG Dialog on Mobile device** - (Landscape Mode)
image

- **LG Dialog Dialog on Tablet device** - (Portrait Mode)

image
image

- **LG Dialog Dialog on Tablet device** - (Landscape Mode)

image
image

-----

**After Enhancement** ScreenShots - 

- **BottomSheet Dialog on Mobile device** - (Portrait Mode)
image
image

- **SideSheet Dialog on Mobile device** - (Landscape Mode)
image
image

- **SideSheet Dialog on Tablet device** - (Portrait Mode)
image
image

- **SideSheet Dialog on Tablet device** - (Landscape Mode)
image
image

### CODE REVIEW

**Comment by SidharthMudgil** [comment]
Why nav rail is not centred in tab layout... Did you change it?

**Comment by dharamveer-gupta** [comment]
> Why nav rail is not centred in tab layout... Did you change it?

No I haven't, Nav rail is untouched. 
Even I also noticed the same in the `main` branch

**Comment by SidharthMudgil** [comment]
can you increase width of the side sheet for tablets... increase around 1.5x

**Comment by dharamveer-gupta** [comment]
> can you increase width of the side sheet for tablets... increase around 1.5x

Below are the screenshot after increasing width of SideSheet around **1.5x** for both Tablet & Mobile devices?

1. on **Mobile device** after increasing it to 1.5x width of SideSheet (Landscape mode)

image

2. on **Tablet device** after increasing it to 1.5x width of SideSheet (Portrait mode)
image

3. on **Tablet device** after increasing it to 1.5x width of SideSheet (Landscape mode)
image

**Pull request merged**
